# Generated by Django 5.0.14 on 2026-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细内容')),
                ('tag', models.CharField(default='未分类', max_length=50, verbose_name='标签')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='已掌握')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '错题/知识点',
                'verbose_name_plural': '错题/知识点',
                'ordering': ['-created_at'],
            },
        ),
    ]
